### ISSUE TITLE
High memory requirement when executing carnival brute force

### ISSUE THREAD

**Issue by AndreWeiner** [rishal-hurbans/Grokking-Artificial-Intelligence-Algorithms#4]
**Problem:**
Executing the script [carnival_bruteforce.py](https://github.com/rishal-hurbans/Grokking-Artificial-Intelligence-Algorithms/blob/master/ch06-swarm_intelligence-ants/carnival_brute_force.py) has extremely high memory requirements such that the process is eventually killed on my system (12 GB RAM).

**Suggestion:**
Use the permutation iterator instead of converting it into a set.

**Comment by rishal-hurbans** [comment]
Thanks for this. It should be resolved. The brute force approach will still be CPU intensive though and potentially take a very long time to complete.
