### ISSUE TITLE
import error: No module named 'ml_data_preparation'

### ISSUE THREAD

**Issue by AndreWeiner** [rishal-hurbans/Grokking-Artificial-Intelligence-Algorithms#5]
**Problem:**
Executing the scripts
- [ml_scikitlearn_linear_regression.py](https://github.com/rishal-hurbans/Grokking-Artificial-Intelligence-Algorithms/blob/master/ch08-machine_learning/linear_regression/ml_scikitlearn_linear_regression.py)
- [ml_scikitlearn_decision_tree_classification.py](https://github.com/rishal-hurbans/Grokking-Artificial-Intelligence-Algorithms/blob/master/ch08-machine_learning/decision_trees/ml_scikitlearn_decision_tree_classification.py)
- [ml_scikitlearn_decision_tree_classification_simple.py](https://github.com/rishal-hurbans/Grokking-Artificial-Intelligence-Algorithms/blob/master/ch08-machine_learning/decision_trees/ml_scikitlearn_decision_tree_classification_simple.py)

leads to the import error
`ModuleNotFoundError: No module named 'ml_data_preparation'`

**Suggestion:**
- rearange folder structure (joint dependencies in subfolder) or
- add parent folder to python path

**Comment by rishal-hurbans** [comment]
Thank you for your feedback Andre. It's much appreciated! I've resolved both this issue and the "High memory requirement when executing carnival brute force" issue that you raised.
