### ISSUE TITLE
ml_scikitlearn_linear_regression code

### ISSUE THREAD

**Issue by hsang** [rishal-hurbans/Grokking-Artificial-Intelligence-Algorithms#8]
Hello Rishal Hurbans,

Firstly, congratulations for your book, it is awesome.

I have a question regarding ml_scikitlearn_linear_regression code.  x is usually used for the columns that we use for prediction and y for the labels we want to predict. However, in the ml_scikitlearn_linear_regression code, reg_test_x is used for price, and reg_test_y is used for carat (lines 26 and 27).  Is it  the other way around? Maybe I am misunderstanding something.

Best,
hsang

**Comment by rishal-hurbans** [comment]
Hi Hsang, 

Apologies for the delay. I also responded to your comments on the Manning discussion forum for the book a short while ago. Thank you for your feedback. I really appreciate it. 

Someone else also raised the inversion of the usual convention for those variables in that chapter. I will look into it, and update this repo when / if the book content is updated. I hope this helps? 

-Rishal

**Comment by hsang** [comment]
Thank you very much for your replies and congratulations again for your awesome book.

**Comment by rishal-hurbans** [comment]
Thank you very much @hsang.
